### ISSUE TITLE
Citation Info Request

### ISSUE THREAD

**Issue by zoeNantes** [Kaketo/bcselector#4]
Dear @Kaketo , i am really grateful to find your post about the different calculations of mutual informations in the directory <bcselector/bcselector/information_theory/basic_approximations.py>. They are tidy and useful. I am planning to reuse these functions for my own algorithm. Could you please offer me further information about the citation of these functions? Are there some paper that i can refer to?  Thanks a lot:)

**Comment by Kaketo** [comment]
Hi! I'm very glad to hear that :)
This project is a part of my Master Thesis which will be published in September this year. To implement these functions I used definitions from the book, very popular in Information Theory:
http://www.cs-114.org/wp-content/uploads/2015/01/Elements_of_Information_Theory_Elements.pdf

Currently, if You want to cite strictly the implementation, the only thing I can offer is to cite my GitHub repository.

Let me know if that satisfies You

**Comment by zoeNantes** [comment]
Hello @Kaketo . Thanks so much for the link of this book. It is really a professional one in this domain, :P whereas i am in the subdomain of NLP. Even though, i am happy to learn about this book. I think i will cite your Github repository if i am lucky enough to publish it. I will let you know if this source are cited:)  Good luck for your Master Thesis 💯

**Comment by Kaketo** [comment]
Thanks and good luck as well :)
